version: '3.8'

services:
  app:
    container_name: app-container
    image: app-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB-URL: jdbc:mysql://db-service:3306/educationdb?serverTimezone=UTC
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
    networks:
      - education-network
    depends_on:
       db-service:
         condition: service_healthy

  db-service:
    container_name: mysql-container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: educationdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - education-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s


networks:
  education-network:
    driver: bridge

volumes:
  mysql-volume: